#  Copyright Epic Games, Inc. All Rights Reserved.
def getPaletteString():



    bgColorA = "rgb(45, 56, 78)"
    scrollWidgetBgColor =  "(35, 45, 55)"
    bgHighlightColorA = "rgb(121, 94, 102)"

    borderDarkColor = "rgb(21, 21, 21)"

    buttonLightColor = "rgb(62, 91, 122)"
    buttonDisabledColor = "rgb(52, 81, 112)"
    buttonLightPressedColor = "rgb(32, 61, 92)"

    fontDarkColor = "rgb(118, 93, 105)"
    fontLightColor = "rgb(201, 201, 201)"

    selectedTabColor = "rgb(253, 251, 212)"
    notSelectedTabColor = "rgb(220, 188, 156)"

    borderStr = "border: 1px groove " + borderDarkColor + ";"

    paletteStr = str(
    "QWidget {font-family: Trebuchet MS; font: bold 11px;}"
    "QMainWindow{" 
        "color: " + bgColorA + ";" 
        "background: " + bgColorA + ";" 
        "border: 0px solid white;"        
        "font: " + fontLightColor + ";" 
    "}" 
    "QLabel{" 
        "color: " + fontLightColor + ";" 
    "}" 
    "QLineEdit{" 
       + borderStr +
        "color: " + fontDarkColor + ";"
        "border-radius: 5px;"
        "background: " + scrollWidgetBgColor + ";" 
        "color: " + fontLightColor + ";" 
    "}" 
    "QPushButton{" 
        "background: " + buttonLightColor + ";" 
        "color: " + fontLightColor + ";"
                                     
        "border-radius: 3px;"
        "padding: 8px;"
        "margin: 1px;"
    "}"
    "QPushButton:pressed{" 
        "background: " + buttonLightPressedColor + ";" 
    "}"
    "QPushButton:!pressed{" 
        "background: " + buttonLightColor + ";" 
    "}"
    "QPushButton:disabled{" 
        "background: " + buttonDisabledColor + ";"
        "color: " + fontDarkColor + ";"
    "}"
    "QCheckBox{"
        "background-color: " + bgColorA + ";"                 
    "}"
    "QMenu{"
        "background-color: " + bgColorA + ";"
        "border: 1px solid " + borderDarkColor + ";"
        "color: " + fontDarkColor + ";"            
    "}"
    "QMenu::item{"
        "color: " + fontLightColor + ";"
    "}"
    "QMenu::item:selected {"
        "background-color: " + bgHighlightColorA + ";"
    "}"
    "QTreeWidget{"
        "background-color: " + scrollWidgetBgColor + ";"
        + borderStr +
        "color: " + fontDarkColor + ";"
        "border-radius: 5px;"
        "margin-top: 3px;"
        "padding: 10px;"
    "}"
    "QTreeWidget::item{"
        "color: " + fontLightColor + ";"
    "}"
    "QTreeWidget::item:selected {"
        "background-color: " + bgHighlightColorA + ";"
    "}"
    "QListWidget{"
        "background-color: " + scrollWidgetBgColor + ";"
        + borderStr +
        "color: " + fontDarkColor + ";"
        "border-radius: 5px;"
        "margin-top: 3px;"
        "padding: 10px;"
    "}"
    "QGroupBox{"
        "background-color: " + bgColorA + ";"
        + borderStr +
        "color: " + fontDarkColor + ";"
        "border-radius: 5px;"
        "margin-top: 10px;"
        "padding: 10px;"
    "}"
    "QGroupBox::title{"
        "subcontrol-origin: margin;"
        "subcontrol-position: top center;"
        "background-color: " + bgColorA + ";"
        + borderStr +
        "color: " + fontLightColor + ";"
        "border-radius: 3px;"
        "padding: 1px 3px;"
    "}"
    "QComboBox{"
        "background: " + buttonLightColor + ";"
        "color: " + fontDarkColor + ";"
        "border-radius: 4px;"
    "}"
    "QComboBox::drop-down {"
        "subcontrol-origin: padding;"
        "subcontrol-position: top right;"
        "border-style: none;"            
    "}"
    "QTabWidget::pane{"
        "background: " + bgColorA + ";"
         + borderStr +
        "color: " + fontDarkColor + ";"
        "border-radius: 5px;"
    "}"
    "QTabWidget::tab-bar {"
        "left: 5px;"
        "padding:0px;"
    "}"
    "QTabBar::tab {"
        "color: " + fontDarkColor + ";"
        "padding:5px;"
        "border-top-left-radius: 4px;"
        "border-top-right-radius: 4px;"
        "border: 1px solid " + borderDarkColor + ";"
    "}"
        "QTabBar::tab:selected{"
        "background: " + selectedTabColor + ";"
    "}"
        "QTabBar::tab:!selected{"
        "background: " + notSelectedTabColor + ";"
    "}")

    return paletteStr
